version: "3.8"

services:
  db:
    image: mysql
    restart: always
    # This is for development only, do not use in production
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev-user
      MYSQL_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d/:ro
      - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
