[server] #nomal type
mode = "dev"
port ":8080"

[db] #이중 map type map[string]map[string]interface{}
[db.mysql]
host = ""
user = ""
pass = ""
name = ""

[db.mongo]
host = ""
user = ""
pass = ""
name = ""

[log]
level = "debug"
fpath = "./logs/go-logger" # 로그가 생성될 경로 ./logs. 로그 파일명 go-logger_xxx.log
msize = 2000 # megabyte = 2g
mage = 7 # 7days
mbackup = 5 # number of log files